[project]
name = "py-http-server"
version = "0.1.0"
description = "social network python http server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "djangorestframework>=3.16.1",
]
