# Generated by Django 5.2.6 on 2025-09-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Obligatory.", null=True),
        ),
    ]
