# Generated by Django 5.2.6 on 2025-09-27 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_options_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional Image",
                null=True,
                upload_to="post-images/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(
                default="default",
                help_text="Title of the post",
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Post must be at least 1 character long."
                    )
                ],
                verbose_name="Title",
            ),
            preserve_default=False,
        ),
    ]
